# Generated by Django 2.2.3 on 2020-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(editable=False, max_length=39)),
                ('by', models.CharField(editable=False, max_length=39)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=39)),
                ('pid', models.CharField(editable=False, max_length=39)),
                ('description', models.CharField(max_length=4000)),
                ('attachment', models.CharField(max_length=550)),
                ('time', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
