# Generated by Django 2.2.3 on 2020-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcoming_feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=39)),
                ('seen', models.BigIntegerField()),
            ],
        ),
    ]
