# Generated by Django 2.2.3 on 2020-01-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authenticate',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(editable=False, max_length=39)),
                ('image', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=12)),
                ('dob', models.CharField(max_length=12)),
                ('regno', models.CharField(editable=False, max_length=10)),
                ('created', models.CharField(editable=False, max_length=10)),
                ('last_login', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=5)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
