# Generated by Django 2.2.3 on 2019-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authenticate',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('_id', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('regno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.CharField(max_length=10)),
                ('last_login', models.CharField(max_length=10)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
