# Generated by Django 2.2.3 on 2019-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='_id',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
