# Generated by Django 2.2.3 on 2019-10-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20191029_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticate',
            old_name='_id',
            new_name='uid',
        ),
    ]
