# Generated by Django 2.2.3 on 2019-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20191029_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='regno',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
