# Generated by Django 2.2.3 on 2019-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20191029_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='uid',
            field=models.CharField(editable=False, max_length=39),
        ),
    ]
