# Generated by Django 2.2.3 on 2019-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20191029_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='created',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
