# Generated by Django 2.2.3 on 2019-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20191029_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authenticate',
            name='regno',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
