# Generated by Django 2.2.3 on 2019-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20191029_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticate',
            name='department',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authenticate',
            name='dob',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
